### ISSUE TITLE
RuntimeError: CGAL ERROR: assertion violation!

### ISSUE THREAD

**Issue by JingMatrix** [eboix/high_precision_barycenters#1]
When I use 'powerdiagram' method, in `example_barycenter_computation.py`,
it gives me following error:
```
Traceback (most recent call last):
  File "/home/jing/Documents/Project/high_precision_barycenters/example_barycenter_computation.py", line 19, in <module>
    bary_prob.solve()
  File "/home/jing/Documents/Project/high_precision_barycenters/MOT_column_generation.py", line 78, in solve
    new_tups=self.cutting_plane_fn(duals)
  File "/home/jing/Documents/Project/high_precision_barycenters/barycenter_separation_oracle.py", line 90, in get_tuples_to_check_from_power_diagram_intersections
    arr.insert(seg)
RuntimeError: CGAL ERROR: assertion violation!
Expr: cv2.is_vertical() ? m_traits.is_in_y_range_2_object()(cv2, *ip) : m_traits.is_in_x_range_2_object()(cv2, *ip)
File: /usr/include/CGAL/Arr_segment_traits_2.h
Line: 731
```

However, the 'native' method works fine.

**Comment by JingMatrix** [comment]
Could be related to 
https://github.com/scikit-geometry/scikit-geometry/issues/62

**Comment by eboix** [comment]
Thanks, I will take a look. I think CGAL is probably throwing a bug because of a degeneracy in your data set: you probably have data-points that are connected by perfectly vertical/horizontal lines, or maybe you have collinear points?

I will think about what I can do to make this more robust, and see if I can make that change.

**Comment by eboix** [comment]
Would it be possible for you to share the dataset for which this issue is happening? Or a minimal example that breaks?

**Comment by JingMatrix** [comment]
Basically, I didn't modify your script `example_barycenter_computation.py`, which generates `5 x 10`
random data each time.
I tried this script many times, each time different random data of course, but none works.
However, the 'naive' method never failed.
So I believe it is a code problem not that related to the radom generated data.
Here is a very small data, generated by your script that does not work:
(k=2, n=4)
```
[array([[-0.96767016, -0.31406105,  1.        ],
       [-0.32037978, -0.2984068 ,  1.        ],
       [ 0.13846891, -0.33982284,  1.        ],
       [ 0.26749442,  0.28096137,  1.        ]]), 
array([[-0.92225222, -0.15008187,  1.        ],
       [ 0.43529417, -0.93174826,  1.        ],
       [ 0.11086826,  0.79881791,  1.        ],
       [ 0.60404668, -0.45836448,  1.        ]])]
```

**Comment by eboix** [comment]
Thanks a lot for letting me know!! It used to work, but maybe the latest version of CGAL broke it? I'll try to push a fix in the coming days.

**Comment by JingMatrix** [comment]
You can close this issue because I will fix this bug in the upstream.
See my pull-request there:
https://github.com/scikit-geometry/scikit-geometry/pull/94

**Comment by eboix** [comment]
Thank you so much!! I really appreciate it. I could not figure out how to fix this. Please let me know if it still does not work.

**Comment by JingMatrix** [comment]
You are welcome, I am doing the same topic for my PhD thesis.
Now your code works perfectly (if the upstream is compiled with my fix).
And I am working on a new algorithm for calculating Wasserstein barycenter.
It won't be too late that we discuss about it again.

**Comment by eboix** [comment]
Looking forward to seeing your work! Many thanks again
